Handraising Website prototype
Scarsdale-Robotics/Remote-Hand-Raising-Frontend pull request #1
Opened 2020-11-09 00:00 UTC by Whackamoley109

2020-11-09 00:16 UTC, Yey007 requested changes
Overall, this is amazing work. The site looks very nice, better than I could ever do it, at least. However, there are a few things that can be done in a cleaner or more readable way. No need to rush the changes though, as this prototype *looks* very well polished and can be used to show it off if needed.

2020-11-09 00:16 UTC, Yey007 commented on brb.php
> +<br>
Same here

2020-11-09 00:16 UTC, Yey007 commented on nav.php
> +                </li>
The indentation here is a little wack, fix it if you can

2020-11-09 00:16 UTC, Yey007 commented on script.js
> +});
Feels like this can be done with CSS like so:
```
.jumbotron {
    height: 100%;
}
```

2020-11-09 00:16 UTC, Yey007 commented on brb.php
> +<br>
Swap this out for CSS

2020-11-09 00:16 UTC, Yey007 commented on brb.php
> +<br>
Same here

2020-11-09 00:16 UTC, Yey007 commented on index.php
> +<br>
Swap this out for CSS

2020-11-09 00:16 UTC, Yey007 commented on index.php
> +<br>
Same here

2020-11-09 00:16 UTC, Yey007 commented on signup.php
> +    <br>
Swap this out for CSS

2020-11-09 00:16 UTC, Yey007 commented on signup.php
> +    <br>
Same here

2020-11-09 00:16 UTC, Yey007 commented on styles.css
> +@font-face {
Perhaps it's better to import all of these fonts from somewhere like google fonts or another repository using `@import`

2020-11-09 00:16 UTC, Yey007 commented on styles.css
> +.navbar-custom .navbar-brand, .navbar-custom .navbar-text, .navbar-custom .navbar-nav, .navbar-custom .navbar-nav, .nav-link {
This file feels very monolithic. Maybe we can split it into multiple files?

2020-11-09 18:24 UTC, ecukier commented on script.js
> +});
jquery go brrrrr

2020-11-09 19:36 UTC, ecukier requested changes

2020-11-09 19:36 UTC, ecukier commented on login.php
> +
This will be done via oauth, not a form. For now, replace with a placeholder image allowed by google https://developers.google.com/identity/branding-guidelines

2020-11-09 19:44 UTC, ecukier commented on login.php
> +
Also as a general note, unless you have a good reason I would keep it in html instead of all files being PHP.

2020-11-11 20:56 UTC, ecukier commented
I'm going to approve this just so we can start with git submodules, but make sure to implement the requested changes.

2020-11-11 20:56 UTC, merged